### ISSUE TITLE
Why pug

### ISSUE THREAD

**Issue by kantum** [timalanfarrow/kratos-selfservice-ui-vue3-typescript#12]
May I ask why pug is used, is it not a templating language as vue is?

Just to be sure I can go ahead and start to translate everything to vue, is there is something special about pug not available in vue that made you choose it?

Thanks

**Comment by timalanfarrow** [comment]
Hi Kantum, sorry for the late response.

Initially I chose pug on the simple basis that I think it's a little more readable than HTML. There is no real benefit in terms of functionality, and later on in the project I had initially built this for, I abandoned Pug as it was causing more problems than it solved. I just haven't come back to refactor everything to HTML.
