### ISSUE TITLE
npm build fails

### ISSUE THREAD

**Issue by CreMindES** [timalanfarrow/kratos-selfservice-ui-vue3-typescript#4]
I've just cloned the repo and tried to build it with Docker. It failed with the following log: [build-error.log](https://github.com/timalanfarrow/kratos-selfservice-ui-vue3-typescript/files/8589455/build-error.log).

```bash
error TS2345: Argument of type 'import("[repo]/node_modules/@ory/kratos-client/dist/api").UiNode' is not assignable to parameter of type 'import("[repo]/node_modules/@ory/client/dist/api").UiNode'.
  Types of property ''attributes'' are incompatible.
    Type 'import("[repo]/node_modules/@ory/kratos-client/dist/api").UiNodeAttributes' is not assignable to type 'import("[repo]/node_modules/@ory/client/dist/api").UiNodeAttributes'.
```

**Comment by timalanfarrow** [comment]
The build should succeed after pulling down from the latest. Looked to be a matter of the project using `@ory/client` for some type imports and `@ory/kratos-client` for others.
